#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Please give a brainfuck file to compile..."
	exit 1
fi


gcc compiler.c -o bfcc.o

./bfcc.o $1
echo "$1.o"
gcc bf.c -o "$(echo "$1" | rev | cut -d'/' -f 1 | rev).o"
rm bfcc.o
rm bf.c

